baseurl: "/Imvertor-organisaties"
# apiname: "BRK Bevragen"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Imvertor documentatie
    path: /test
    subnav:
      - title: Algemeen
        path: /
      - title: Kadaster specifieke documentatie
        url: https://melsk-r.github.io/Kadaster/
        path: /kadaster
      - title: Geonovum specifieke documentatie
        url: https://melsk-r.github.io/Geonovum/index
        path: /geonovum
      - title: VNG Realisatie specifieke documentatie
        url: https://melsk-r.github.io/VNG-Realisatie/
        path: /vng-realisatie
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  
remote_theme: melsk-r/Imvertor-jekyll-theme

github: melsk-r/Imvertor-organisaties

theme: jekyll-theme-time-machine

project_name: /Imvertor
