baseurl: "/Imvertor-organisaties"
# apiname: "BRK Bevragen"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Imvertor documentatie
    path: /
  - title: Kadaster specifieke documentatie
    path: /kadaster/kadaster
  - title: Geonovum specifieke documentatie
    path: /geonovum/geonovum
  - title: VNG Realisatie specifieke documentatie
    subnav:
      - title: Installatie
        path: ./vng-realisatie/installatie
#      - title: Begrippen
#        path: /vng-realisatie/begrippen
#      - title: Het drie-lagen model
#        path: /vng-realisatie/het-3-lagen-model
#      - title: De nieuwe werkwijze
#        path: /vng-realisatie/de-nieuwe-werkwijze
#      - title: Handreikingen
#        path: /vng-realisatie/handreikingen
#      - title: Wetenswaardigheden en specials
#        path: /vng-realisatie/wetenswaardigheden-en-specials
#      - title: Tagged Values
#        path: /vng-realisatie/tagged-values
#       - title: Veel voorkomende foutens
#        path: /vng-realisatie/veel-voorkomende-fouten
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  
remote_theme: melsk-r/Imvertor-jekyll-theme

github: melsk-r/Imvertor-organisaties

theme: jekyll-theme-time-machine

project_name: /Imvertor
